import type { Hospital } from '../types'

export const HOSPITALS: Hospital[] = [
  // 서울 권역
  { id: 'seoul-national', name: '서울대학교병원', region: '서울',
    websiteUrl: 'https://www.snuh.org', hrPageUrl: 'https://www.snuh.org/recruit/main.do',
    searchKeywords: ['서울대학교병원', '서울대병원'] },
  { id: 'asan-medical', name: '서울아산병원', region: '서울',
    websiteUrl: 'https://www.amc.seoul.kr', hrPageUrl: 'https://www.amc.seoul.kr/asan/job/main.do',
    searchKeywords: ['서울아산병원', '아산병원'] },
  { id: 'samsung-medical', name: '삼성서울병원', region: '서울',
    websiteUrl: 'https://www.samsunghospital.com',
    searchKeywords: ['삼성서울병원', '삼성병원'] },
  { id: 'severance', name: '세브란스병원', region: '서울',
    websiteUrl: 'https://www.severance.or.kr', hrPageUrl: 'https://www.yuhs.ac/recruit/',
    searchKeywords: ['세브란스병원', '연세대학교의과대학부속세브란스'] },
  { id: 'seoul-st-marys', name: '서울성모병원', region: '서울',
    websiteUrl: 'https://www.cmcseoul.or.kr',
    searchKeywords: ['서울성모병원', '가톨릭대학교서울성모'] },
  { id: 'gangnam-severance', name: '강남세브란스병원', region: '서울',
    websiteUrl: 'https://gs.yuhs.ac', searchKeywords: ['강남세브란스병원'] },
  { id: 'boramae', name: '서울특별시보라매병원', region: '서울',
    websiteUrl: 'https://www.boramae.snu.ac.kr', searchKeywords: ['보라매병원', '서울특별시보라매병원'] },
  { id: 'korea-anam', name: '고려대학교안암병원', region: '서울',
    websiteUrl: 'https://anam.kumc.or.kr', searchKeywords: ['고려대학교안암병원', '안암병원'] },
  { id: 'korea-guro', name: '고려대학교구로병원', region: '서울',
    websiteUrl: 'https://guro.kumc.or.kr', searchKeywords: ['고려대학교구로병원', '구로병원'] },
  { id: 'hanyang-univ', name: '한양대학교병원', region: '서울',
    websiteUrl: 'https://www.hyuh.com', searchKeywords: ['한양대학교병원', '한양대병원'] },
  { id: 'kyunghee-univ', name: '경희대학교병원', region: '서울',
    websiteUrl: 'https://www.khmc.or.kr', searchKeywords: ['경희대학교병원', '경희대병원'] },
  { id: 'ewha-seoul', name: '이대서울병원', region: '서울',
    websiteUrl: 'https://www.emc.ewha.ac.kr', searchKeywords: ['이대서울병원', '이화여자대학교부속서울병원'] },
  { id: 'chungang-univ', name: '중앙대학교병원', region: '서울',
    websiteUrl: 'https://www.cauhs.or.kr', searchKeywords: ['중앙대학교병원', '중앙대병원'] },
  { id: 'kangbuk-samsung', name: '강북삼성병원', region: '서울',
    websiteUrl: 'https://www.kbsmc.co.kr', searchKeywords: ['강북삼성병원'] },
  { id: 'soonchunhyang-seoul', name: '순천향대학교부속서울병원', region: '서울',
    searchKeywords: ['순천향대학교부속서울병원', '순천향서울병원'] },
  // 경기/인천 권역
  { id: 'bundang-snuh', name: '분당서울대학교병원', region: '경기',
    websiteUrl: 'https://www.snubh.org', hrPageUrl: 'https://www.snubh.org/intro/recruit.do',
    searchKeywords: ['분당서울대학교병원', '분당서울대병원'] },
  { id: 'ajou-univ', name: '아주대학교병원', region: '경기',
    websiteUrl: 'https://www.ajoumc.or.kr', searchKeywords: ['아주대학교병원', '아주대병원'] },
  { id: 'gachon-gil', name: '가천대길병원', region: '인천',
    websiteUrl: 'https://www.gilhospital.com', searchKeywords: ['가천대길병원', '길병원'] },
  { id: 'inha-univ', name: '인하대학교병원', region: '인천',
    websiteUrl: 'https://www.inha.com', searchKeywords: ['인하대학교병원', '인하대병원'] },
  { id: 'soonchunhyang-bucheon', name: '순천향대학교부속부천병원', region: '경기',
    searchKeywords: ['순천향대학교부속부천병원', '순천향부천병원'] },
  { id: 'korea-ansan', name: '고려대학교안산병원', region: '경기',
    websiteUrl: 'https://ansan.kumc.or.kr', searchKeywords: ['고려대학교안산병원', '안산병원'] },
  { id: 'hallym-sungsim', name: '한림대학교성심병원', region: '경기',
    searchKeywords: ['한림대학교성심병원', '한림성심병원'] },
  { id: 'wonkwang-sanbon', name: '원광대학교산본병원', region: '경기',
    searchKeywords: ['원광대학교산본병원', '원광산본병원'] },
  // 강원 권역
  { id: 'kangwon-univ', name: '강원대학교병원', region: '강원',
    websiteUrl: 'https://hosp.kangwon.ac.kr', searchKeywords: ['강원대학교병원'] },
  { id: 'wonju-severance', name: '연세대학교원주세브란스기독병원', region: '강원',
    websiteUrl: 'https://www.wkuh.org', searchKeywords: ['원주세브란스기독병원', '원주세브란스'] },
  // 충청 권역
  { id: 'chungnam-univ', name: '충남대학교병원', region: '충청',
    websiteUrl: 'https://www.cnuh.co.kr', searchKeywords: ['충남대학교병원', '충남대병원'] },
  { id: 'konyang-univ', name: '건양대학교병원', region: '충청',
    websiteUrl: 'https://www.kyuh.ac.kr', searchKeywords: ['건양대학교병원'] },
  { id: 'dankook-univ', name: '단국대학교병원', region: '충청',
    websiteUrl: 'https://www.dankookhospital.or.kr', searchKeywords: ['단국대학교병원', '단국대병원'] },
  { id: 'soonchunhyang-cheonan', name: '순천향대학교부속천안병원', region: '충청',
    searchKeywords: ['순천향대학교부속천안병원', '순천향천안병원'] },
  { id: 'chungbuk-univ', name: '충북대학교병원', region: '충청',
    websiteUrl: 'https://hosp.chungbuk.ac.kr', searchKeywords: ['충북대학교병원', '충북대병원'] },
  // 전라 권역
  { id: 'chonnam-univ', name: '전남대학교병원', region: '전라',
    websiteUrl: 'https://www.cnuh.com', searchKeywords: ['전남대학교병원', '전남대병원'] },
  { id: 'jeonbuk-univ', name: '전북대학교병원', region: '전라',
    websiteUrl: 'https://www.jbuh.ac.kr', searchKeywords: ['전북대학교병원', '전북대병원'] },
  { id: 'chosun-univ', name: '조선대학교병원', region: '전라',
    websiteUrl: 'https://www.chosun.ac.kr/medical', searchKeywords: ['조선대학교병원'] },
  { id: 'hwasoon-chonnam', name: '화순전남대학교병원', region: '전라',
    websiteUrl: 'https://cnuhws.com', searchKeywords: ['화순전남대학교병원', '화순전남대병원'] },
  // 대구/경북 권역
  { id: 'kyungpook-univ', name: '경북대학교병원', region: '대구',
    websiteUrl: 'https://www.knuh.kr', searchKeywords: ['경북대학교병원', '경북대병원'] },
  { id: 'keimyung-dongsan', name: '계명대학교동산병원', region: '대구',
    websiteUrl: 'https://www.dsmc.or.kr', searchKeywords: ['계명대학교동산병원', '동산병원'] },
  { id: 'yeungnam-univ', name: '영남대학교병원', region: '대구',
    websiteUrl: 'https://www.ynu.ac.kr', searchKeywords: ['영남대학교병원', '영남대병원'] },
  { id: 'chilgok-kyungpook', name: '칠곡경북대학교병원', region: '대구',
    websiteUrl: 'https://www.cgknuh.kr', searchKeywords: ['칠곡경북대학교병원', '칠곡경북대병원'] },
  { id: 'daegu-catholic', name: '대구가톨릭대학교병원', region: '대구',
    websiteUrl: 'https://www.dcmc.co.kr', searchKeywords: ['대구가톨릭대학교병원', '대구가톨릭병원'] },
  // 부산/경남 권역
  { id: 'pusan-univ', name: '부산대학교병원', region: '부산',
    websiteUrl: 'https://www.pnuh.co.kr', searchKeywords: ['부산대학교병원', '부산대병원'] },
  { id: 'dongah-univ', name: '동아대학교병원', region: '부산',
    websiteUrl: 'https://www.dahl.co.kr', searchKeywords: ['동아대학교병원', '동아대병원'] },
  { id: 'kosin-gospel', name: '고신대학교복음병원', region: '부산',
    websiteUrl: 'https://www.kosinmed.or.kr', searchKeywords: ['고신대학교복음병원', '고신복음병원'] },
  { id: 'yangsan-pusan', name: '양산부산대학교병원', region: '경남',
    websiteUrl: 'https://www.yangsan.pnuh.co.kr', searchKeywords: ['양산부산대학교병원', '양산부산대병원'] },
  { id: 'gyeongsang-national', name: '경상국립대학교병원', region: '경남',
    websiteUrl: 'https://www.gnuh.co.kr', searchKeywords: ['경상국립대학교병원', '경상대병원'] },
  // 제주 권역
  { id: 'jeju-univ', name: '제주대학교병원', region: '제주',
    websiteUrl: 'https://hosp.jejunu.ac.kr', searchKeywords: ['제주대학교병원', '제주대병원'] },
]

export const HOSPITAL_MAP = new Map(HOSPITALS.map(h => [h.id, h]))
export const HOSPITAL_KEYWORDS = HOSPITALS.flatMap(h =>
  h.searchKeywords.map(kw => ({ keyword: kw, hospital: h }))
)
